### ISSUE TITLE
Create a deploy script

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#100]
Right now, I have Semaphore set up to automatically deploy to the staging environment and it runs these commands:

```
git push --force heroku $BRANCH_NAME:master
heroku pg:reset DATABASE --app greensteps-staging --confirm greensteps-staging
heroku run rake db:schema:load db:populate --app greensteps-staging
```

After I look over the staging environment, I then promote from staging to production using the Heroku web interface. Then I run migrations in production (from the command line). It would be good to have a script to do this and it should also run after party tasks. You can promote a slug via Heroku CLI (`heroku pipelines:promote`).

@invacuo - can I get your input on this?

**Comment by invacuo** [comment]
I am not too familiar with Semaphore. The after_party tasks need to be run after the migrations have been run. I will try to do some reading about how Semaphore handles deploys and see where we can add running the migrations as well as after_party into the deploy script.
