### ISSUE TITLE
Admins can edit prizes

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#140]

**Comment by jdg006** [comment]
I would be happy to take a crack at this issue. I have never created a pull request for an open source project before and was told this was a good place to start. Let me know if you have any problems with me trying to take on this issue and if you have any advice/warnings for me.

**Comment by crawfoal** [comment]
@jdg006 Glad to have you here! 

As far as advice/warnings go, the only thing I can think of right now is that I'm planning on pulling out the translation setup very soon (in the next few days), so don't spend a ton of time learning about that if you don't already know it. In fact, you can just put plain old strings in there (even though it says throughout this project not to do that).

**Comment by jdg006** [comment]
I have completed the feature, but I'm going through the steps to submit the pull request and one of those requirements is that I install the docker image for code climate cli. I am using cloud 9 IDE and it does not support docker which (i think) I need to install the docker image for code climate. Let me know if you have run into this problem before or if there are any workarounds or if I can forgo this step.

**Comment by crawfoal** [comment]
Oh, I should have made this more clear. Opening a PR will trigger Code Climate to run an analysis, so after a couple minutes, you'll see results right there in the PR summary. No need to set up Code Climate locally unless you want a quicker feedback loop 🙂

**Comment by crawfoal** [comment]
Also, I keep going back and forth about keeping I18n in there. Right now I'm back to leaning towards keeping it. Let me know if you need help with that.
