### ISSUE TITLE
Require rails in bin/setup?

### ISSUE THREAD

**Issue by pierce-m** [crawfoal/greensteps#157]
Hi, when I ran ./bin/setup I got the following error:

```
./bin/setup:33:in `block in <main>': uninitialized constant Rails (NameError)
	from /home/pierce/.rbenv/versions/2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /home/pierce/.rbenv/versions/2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from ./bin/setup:13:in `<main>'
```

I fixed this by adding `require 'rails'` to the top of the file. Do we need to add this or is something wrong with my environment somehow?

**Comment by crawfoal** [comment]
Sorry about that... it is from environment line 33. Not sure how I missed this 🙁 

I don't think we should require rails since it would only be used to check the environment. We can probably find another way of making sure that the production database wouldn't be populated with sample data.

**Comment by crawfoal** [comment]
I'm just going to remove that line from the setup script. If someone wants sample data, it's easy enough to run the rake task separately.
