### ISSUE TITLE
Users can get a maximum of 30 points per month

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#162]
Description Update:

The fix for this issue should include two features related to user experience.

1. Suppose a user with X points attempts to log Y trash bags such that X + Y > 30. Then the desired behavior, instead of rejecting the submission completely, is to grant |30 - X| points (the amount necessary to make a total of 30), and report that Y - (30 - X) trash bags were not logged in accordance with the maximum point policy. ~This should also include a numericality validation to ensure values higher than 30 are never submitted.~

2. Once a user has reached 30 points, the log button should be disabled.

**Comment by pierce-m** [comment]
I'll start on this tomorrow, seems like it shouldn't be too hard
