### ISSUE TITLE
Rake task to create admins

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#37]

**Comment by k1r8r0wn** [comment]
Hi, @crawfoal !

If you like, I can help with all Admin's staff as Hactoberfest participant.

**Comment by crawfoal** [comment]
That would be great, thanks!

For the admin stuff, I'm not planning on using an admin Rails gem, I'm just planning on creating a Devise model for the admins, but without a sign-up page, which is where this issue is coming from. I'll get together the basic stuff for the admin model this weekend. If you want to start this issue now, you could stub out the admin stuff you need. If you've already started and are adding the admin model stuff in this PR, let me know so I don't duplicate that work :)

**Comment by k1r8r0wn** [comment]
@crawfoal Please continue your work & I'll add permissions in #38, #39 tasks. According to this, #37 one, you only need ability to auto-create admin users to db, correct?

**Comment by crawfoal** [comment]
I'm not quite sure what you mean when you say "ability to auto-create admin users to db", so just to clarify, what I had in mind is that the rake task would take in an email as a parameter and would create the user (in the db) with a random, temporary password. I'm not sure if Devise has a way of dealing with temporary passwords or not, so that's something to look into. If we need to build that in ourselves, then that should go in a separate PR probably.

**Comment by k1r8r0wn** [comment]
I've meant the same, just the creation of basic admin accounts, it could simply be done with `seeds`.

**Comment by crawfoal** [comment]
Hey so as I look into this more, I'm thinking it might be cleaner to use just one Devise model rather than having both an Admin model and a User model. Admins would just have an 'admin' role which would grant them access to admin functionality. If we go this route, "creating an admin" would really mean just assigning the admin role to an existing user.

Sorry to completely change things up on you... I feel like this issue isn't really ready yet. I'm pretty good at updating issues with the "ready" label when I feel that are ready for help, but I think maybe the "ready" label needs to be mentioned in the contribution guidelines.

**Comment by k1r8r0wn** [comment]
Yeah, maybe you're right. Btw, I thinks it'll be suitable to use this [Pundit gem](https://github.com/elabs/pundit) for authorization purposes. And [Rolify](https://github.com/RolifyCommunity/rolify) for roles library.

**Comment by crawfoal** [comment]
That's exactly what I was thinking! 😃 

Also, I created issue #48 so that this sort of thing will be less likely to happen in the future.
