### ISSUE TITLE
Admins can view a list of all admins

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#38]

**Comment by bhavyanshu** [comment]
I can help with this one. Can I get more details on this one?

**Comment by crawfoal** [comment]
@bhavyanshu It's great to have you here!

Here are few more details that will be helpful:
- functionality that should be restricted to admins (including viewing a list of all admins) should be implemented in a controller in the `Admin` namespace and inherit from `AdminController`
- we've started an admin dashboard, but right now it just shows all the prizes that have been defined; I think it makes sense to link to add a link that will take them to see the list of admins

Other than those two things, I would be good to take a look through the source code so you can see how things are being done in this project. Also make sure you've read the [Pull Request Guidelines](https://github.com/crawfoal/greensteps/blob/master/CONTRIBUTING.md#pull-request-guidelines) and [Running Specs](https://github.com/crawfoal/greensteps/blob/master/CONTRIBUTING.md#running-specs) sections in the contribution guidelines 🙂 

If you have any other questions, let me know!
