### ISSUE TITLE
Only logged in users should be able to view their dashboard

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#4]
Right now, trying that causes an application error. Instead, it should just redirect to the welcome page and show an error message.

**Comment by lukyans** [comment]
https://github.com/crawfoal/greensteps/issues/4

**Comment by lukyans** [comment]
I'd be interested in taking this one

**Comment by crawfoal** [comment]
Sounds good! I'm thinking that only the welcome page will be available to non logged in users.
