### ISSUE TITLE
Test environment still has pending migrations, plus Rails env is dropped from schema

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#41]
After running migrations via `bin/rake db:migrate`, I'm seeing this when I try to run specs:

```
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=test
```
It looks like [this will be fixed by the next release of DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner/pull/487). Until then, we can exclude ar_internal_metadata from any truncation or deletion cleaning done by DatabaseCleaner.

Additionally, it says that the test environment still has pending migrations... but this should have been fixed in PR #34. Any thoughts @stevensona ?

**Comment by stevensona** [comment]
I'm unable to reproduce the issue on a fresh environment. I am running these commands:
```
bundle exec rails db:drop db:create db:migrate
bundle exec rspec
bundle exec rails db:drop db:create db:migrate
bundle exec rspec
bundle exec rails db:drop db:create db:migrate
bundle exec rspec
... etc
```
Can you show the the entire output?

**Comment by crawfoal** [comment]
I've uploaded [a gist of my output](https://gist.github.com/crawfoal/6400efe43a23d533f19df4e2e4b5963f). I see the same behavior when I use `bundle exec ...` instead of `bin/...`.

**Comment by stevensona** [comment]
I was able to reproduce when migrating the db using the command you used ```bin/rake db:migrate``` however executing ```rails db:migrate``` works on my end. I was under the impression that rails db:migrate just invoked the rake task but perhaps something else is going on here.

Can you try running rails db:migrate instead of rake db:migrate and see if you get the same results?

**Comment by crawfoal** [comment]
Yep, the same thing happens 🙁  I was hoping that would do it...

**Comment by stevensona** [comment]
Just tried again and can't reproduce it. Ugh.

**Comment by crawfoal** [comment]
Are you trying with your original set of commands, or an actual migration now?

Also, I tried using the master branch of DatabaseCleaner, and it didn't fix the environment thing 🙁

**Comment by stevensona** [comment]
I've tried everything and have only been able to reproduce the issue using the set of commands from your log (rails g devise admin, migrate, rspec), but now trying again, it works. Have you tried stopping spring, rebundling, bundle update, etc?

**Comment by crawfoal** [comment]
Yep, and I've tried upgrading to Rails 5.1 too.

**Comment by stevensona** [comment]
Very bizarre. Some googling turned up something interesting
https://stackoverflow.com/questions/38209186/rails-5-rspec-environment-data-not-found-in-the-schema suggests what you said in the original comment with regards to ignoring ar_internal_metadata on the database_cleaner truncation cleaner.

**Comment by crawfoal** [comment]
So I think I figured it out. Between my trials, I was using the `reset` task instead of `drop`, `create`, and `migrate`. The `reset` task uses `db:schema:load` instead of `db:migrate`. It looks like after a database has been dropped and recreated, `db:schema:load` will mistakenly mark the test database as development:

```
amandacrawford (issue-41 *) greensteps $ bin/rake db:reset
Running via Spring preloader in process 23400
Dropped database 'greensteps_development'
Dropped database 'greensteps_test'
Created database 'greensteps_development'
Created database 'greensteps_test'
-- enable_extension("plpgsql")
   -> 0.0264s
-- create_table("deeds", {:force=>:cascade})
   -> 0.0149s
-- create_table("users", {:force=>:cascade})
   -> 0.0241s
-- add_foreign_key("deeds", "users")
   -> 0.0031s
-- enable_extension("plpgsql")
   -> 0.0599s
-- create_table("deeds", {:force=>:cascade})
   -> 0.0128s
-- create_table("users", {:force=>:cascade})
   -> 0.0157s
-- add_foreign_key("deeds", "users")
   -> 0.0158s
amandacrawford (issue-41 *) greensteps $ bin/rails db test
psql (9.6.5, server 9.6.2)
Type "help" for help.

greensteps_test=# SELECT * FROM ar_internal_metadata;
     key     |    value    |         created_at         |         updated_at         
-------------+-------------+----------------------------+----------------------------
 environment | development | 2017-10-02 02:14:59.184642 | 2017-10-02 02:14:59.184642
(1 row)
```

**Comment by crawfoal** [comment]
https://github.com/rails/rails/issues/26731

**Comment by stevensona** [comment]
I've been burned by db:reset too many times I've just stopped using it. Glad you figured it out.
