### ISSUE TITLE
Convert all haml files back to erb

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#44]
I think that ERB will be more familiar and approachable to new developers.

**Comment by xdega** [comment]
@crawfoal As much as I prefer HAML syntax, I think I can nail this one really quick. Yay for Hacktoberfest.

**Comment by cmckni3** [comment]
I prefer [Slim](https://github.com/slim-template/slim)

**Comment by xdega** [comment]
@cmckni3 Unrelated, I am interested in looking more into Slim. Does it have support for rails 5.1? Their documentation specifies `3 and 4`... so it's a little confusing.

**Comment by cmckni3** [comment]
The documentation probably isn't updated. I added Rails 5 support to `slim-rails` last year. https://github.com/slim-template/slim-rails/pull/123
