### ISSUE TITLE
Fix styling on devise form errors

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#45]
In commit c26c8, I added an errors partial for form errors and styled it, but I forgot that Devise uses `#error_explanation` to wrap it's form errors. We should add styling back in for these divs (e.g. try to update an user's password, but don't enter the current password), and keep the new styling we have for our errors (e.g. when creating a "deed" enter zero for both trash bags and miles).

**Comment by sundus-y** [comment]
I got this
