### ISSUE TITLE
Contribution guidelines should mention the "ready" label for issues

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#48]
In general, I'll update an issue with labels, including the "ready" label, when I feel it is ready for someone to start working on making the changes. We should mention this in the contribution guidelines.

**Comment by divyanshumehta** [comment]
Can I work on this issue?

**Comment by crawfoal** [comment]
Oops, looks like this issue didn't get closed when the corresponding PR was merged in 🙁 

I encourage you to look and see if there is another issue you'd like to work on 🙂
