### ISSUE TITLE
Remove haml-rails gem

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#51]
We're back to using ERB, so we should remove the `haml-rails` gem and ensure that views are generated using erb and not haml.

**Comment by ThiagosLima** [comment]
May I take this issue?

**Comment by crawfoal** [comment]
That would be great! Thanks :)

**Comment by k1r8r0wn** [comment]
@crawfoal Why not using Slim? :)

**Comment by wiskirz** [comment]
#55 fixes this issue

**Comment by crawfoal** [comment]
@ThiagosLima had you already started working on this?

@wiskirz I appreciate your contribution, but I ask that you review our [contribution guidelines](https://github.com/crawfoal/greensteps/blob/master/CONTRIBUTING.md). In order to avoid situations like these, we are requesting that people "claim" an issue before starting to work on it, just like @ThiagosLima did above.

**Comment by crawfoal** [comment]
Okay, sounds good 🙂

**Comment by wiskirz** [comment]
@crawfoal @ThiagosLima sorry about that

**Comment by ankitbhardwaj78** [comment]
can i work on it @crawfoal

**Comment by crawfoal** [comment]
Thanks @ankitbhardwaj78, but I think that @wiskirz is still working on it.

**Comment by ankitbhardwaj78** [comment]
okkk.... if he is not please let me know
