### ISSUE TITLE
Contributing guidelines should instruct devs to use feature branches

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#56]
At this time, when developers open a pull request from their master branch, Heroku review apps don't automatically deploy PR updates. If the compare branch is not master, then updates to the PR will automatically deploy (after the initial manual deploy).

**Comment by jm96441n** [comment]
@crawfoal just want to clarify for myself so the documentation should tell developers to open a PR against a branch that is not `master` so the PR apps automatically deploy, right?

**Comment by crawfoal** [comment]
Not quite, on their fork they should make the changes in a branch other than master (e.g. `issue-9` or `feature-abc`). They should still open the pull request with `crawfoal/master` as the base to compare with.

**Comment by jm96441n** [comment]
Gotcha, thanks for clarifying! I'll update that PR when I have some free time later today

**Comment by jm96441n** [comment]
PR is updated! Let me know if there are any other changes you'd like.
