### ISSUE TITLE
Organize the Gemfile

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#60]
We should take the gems that are listed at the bottom of the file and add them in the correct category above. The first group should have gems that are used in all environments, the next group should have gems that are used only in the development and testing environments, and then the last group should have gems that are used only in the development environment.

Our RuboCop config is set to order the gems in each group alphabetically. You don't have to do this by hand - just run `bin/rake` after you change the file and RuboCop will alphabetize each group for you. I think RuboCop considers groups to be separated by empty lines. I'm not sure how it would handle the full line comments above the gems, we should probably just delete them. They are there from when the Rails app was generated.

We should delete gems that are commented out.

**Comment by Oneill38** [comment]
I'm on it 👍

**Comment by keepitrio** [comment]
I will take this! This is my first time contributing :)

**Comment by keepitrio** [comment]
I made the [PR](https://github.com/crawfoal/greensteps/pull/61)!
