### ISSUE TITLE
Wrong model used in Deed form page object for I18N strings

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#62]
In the `DeedForm` page object (`spec/page_objects/deed_form.rb`), we get the input labels via `User.human_attribute_name` but it should actually be `Deed.human_attribute_name`. We should figure out why the specs are passing anyways and then use the correct version.

**Comment by Atul9** [comment]
@crawfoal the ActiveModel method `human_attribute_name` transforms attribute names into a human-readable format. It's not mandatory that the param passed to the method should be an attribute of the model.     
```
[3] pry(main)> Deed.human_attribute_name(:miles)
=> "Miles"
[4] pry(main)> User.human_attribute_name(:miles)
=> "Miles"
[5] pry(main)> User.human_attribute_name(:miles) == Deed.human_attribute_name(:miles)
=> true
```

**Comment by crawfoal** [comment]
I had a feeling it was something like that 🙂  I'm going to add the first timers label to this since it will be so easy to fix, but if you want to make the change, feel free 🙂
