### ISSUE TITLE
Enable recovery module in devise

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#87]

**Comment by mostriki** [comment]
@crawfoal could you please clarify? Are you looking for a password recovery module to allow users to recover their forgotten passwords?

**Comment by crawfoal** [comment]
@mostriki Yep, that's correct

**Comment by mostriki** [comment]
Thanks. I will try to tackle that.

**Comment by crawfoal** [comment]
Sounds good, thanks!

**Comment by crawfoal** [comment]
I believe this has been finished already.
