### ISSUE TITLE
Remove ipsum lorem from navigation drawer

### ISSUE THREAD

**Issue by crawfoal** [crawfoal/greensteps#95]

**Comment by akc52** [comment]
Is this still an issue? I could not find any lorem ipsum

**Comment by crawfoal** [comment]
Hi @akc52 - glad to have you here 🙂 

Things like "Link A" and "Users only link 1" should be removed. We should also put the Greensteps logo at the top of the nav drawer and the app bar. I'll upload the logo as soon as I get it from Alyssa. The app bar and nav drawer are defined in [app/views/shared/_appbar.html.erb](https://github.com/crawfoal/greensteps/blob/master/app/views/shared/_appbar.html.erb).
